apiVersion: v1
kind: Service
metadata:
  name: mysql-money-movement
spec:
  type: ClusterIP
  selector:
    app: mysql-money-movement
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP